package inventory.model;
// Generated 7 janv. 2013 21:12:29 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTS")
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String idTag;
	private String libelle;
	private String designation;
	private float prix;
	private float quantite;
	private String fournisseur;
	private Famille famille;
	private Stock stock;
	// private Set<Alerte> alertes= new HashSet<Alerte>();
	private Set<Transaction> transactions = new HashSet<Transaction>();

	public Product() {
	}

	public Product(int id) {
		this.id = id;
		this.idTag = "";
		this.libelle = "";
		this.designation = "";
		this.prix = 0;
		this.fournisseur = "";
	}

	public Product(int id, String idTag) {
		this.id = id;
		this.idTag = idTag;
		this.libelle = "";
		this.designation = "";
		this.prix = 0;
		this.fournisseur = "";
	}

	public Product(int id, String idTag, String libelle, String designation, float prix, String fournisseur,
			Famille famille) {
		this.id = id;
		this.idTag = idTag;
		this.libelle = libelle;
		this.designation = designation;
		this.prix = prix;
		this.fournisseur = fournisseur;
		this.famille = famille;
	}

	public Product(String idTag, String libelle, String designation, float prix, String fournisseur, Famille famille) {
		this.id = -1;
		this.idTag = idTag;
		this.libelle = libelle;
		this.designation = designation;
		this.prix = prix;
		this.fournisseur = fournisseur;
		this.famille = famille;
	}

	public Product(int id, String idTag, String libelle, String designation, float prix, float quantite,
			String fournisseur, Famille famille, Stock stock, Set<Transaction> transactions) {
		this.id = id;
		this.idTag = idTag;
		this.libelle = libelle;
		this.designation = designation;
		this.prix = prix;
		this.quantite = quantite;
		this.fournisseur = fournisseur;
		this.famille = famille;
		this.stock = stock;
		this.transactions = transactions;
	}

	public Product(String idTag, String libelle, String designation, float prix, float quantite, String fournisseur,
			Famille famille, Stock stock, Set<Transaction> transactions) {
		this.id = -1;
		this.idTag = idTag;
		this.libelle = libelle;
		this.designation = designation;
		this.prix = prix;
		this.quantite = quantite;
		this.fournisseur = fournisseur;
		this.famille = famille;
		this.stock = stock;
		this.transactions = transactions;
	}

	// public Product(String idTag, String libelle, String designation, float
	// prix, float quantite, String fournisseur,
	// Famille famille, Stock stock, Set<Alerte> alertes, Set<Transaction>
	// transactions) {
	// super();
	// this.idTag = idTag;
	// this.libelle = libelle;
	// this.designation = designation;
	// this.prix = prix;
	// this.quantite = quantite;
	// this.fournisseur = fournisseur;
	// this.famille = famille;
	// this.stock = stock;
	// this.alertes = alertes;
	// this.transactions = transactions;
	// }

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "IDTAG", unique = true, nullable = false, length = 100)
	public String getIdTag() {
		return this.idTag;
	}

	public void setIdTag(String idTag) {
		this.idTag = idTag;
	}

	@Column(name = "LIBELLE", nullable = false, length = 25)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "DESIGNATION", nullable = false, length = 25)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "PRIX", nullable = false)
	public float getPrix() {
		return this.prix;
	}

	public void setPrix(float prix) {
		this.prix = prix;
	}

	@Column(name = "QUANTITE", nullable = false, length = 25)
	public float getQuantite() {
		return quantite;
	}

	public void setQuantite(float quantite) {
		this.quantite = quantite;
	}

	@Column(name = "FOURNISSEUR", nullable = false, length = 25)
	public String getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(String fournisseur) {
		this.fournisseur = fournisseur;
	}

	@ManyToOne
	@JoinColumn(name = "STOCK_ID", nullable = true)
	public Stock getStock() {
		return stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@ManyToOne
	@JoinColumn(name = "FAMILLE_ID", nullable = false)
	public Famille getFamille() {
		return famille;
	}

	public void setFamille(Famille famille) {
		this.famille = famille;
	}

	// @OneToMany(mappedBy = "produit")
	// public Set<Alerte> getAlertes() {
	// return alertes;
	// }
	//
	// public void setAlertes(Set<Alerte> alertes) {
	// this.alertes = alertes;
	// }

	// @ManyToMany(cascade = CascadeType.ALL)

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinTable(name = "TRANSACTIONS_PRODUCTS", joinColumns = {
			@JoinColumn(name = "ID", nullable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "TRANSACTION_ID", nullable = false) })

	public Set<Transaction> getTransactions() {
		return transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
